spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simplesns?serverTimezone=Asia/Seoul
    username: root
    password: "ssafy"

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:mybatis-config.xml